---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: aws-iam-authenticator-sso-wrapper
    app.kubernetes.io/name: aws-iam-authenticator-sso-wrapper
  name: aws-iam-authenticator-sso-wrapper
  namespace: aws-iam-authenticator-sso-wrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-iam-authenticator-sso-wrapper
  template:
    metadata:
      labels:
        app: aws-iam-authenticator-sso-wrapper
    spec:
      serviceAccountName: aws-iam-authenticator-sso-wrapper
      containers:
        - name: aws-iam-authenticator-sso-wrapper
          image: "aws-iam-authenticator-sso-wrapper"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
          command: ["./aws-iam-authenticator-sso-wrapper"]
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
